/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.inder.customcomponents;

/**
 *
 * @author ISanhot
 */
public class CustomTextAndHelp extends javax.swing.JPanel {

    /**
     * Creates new form CustomTextAndHelp
     */
    public CustomTextAndHelp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textField = new com.inder.customcomponents.ITextField();
        helpbutton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(500, 500));

        textField.setPreferredSize(new java.awt.Dimension(200, 22));
        add(textField);

        helpbutton.setLabel("..");
        helpbutton.setName("help"); // NOI18N
        helpbutton.setPreferredSize(new java.awt.Dimension(20, 20));
        helpbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpbuttonActionPerformed(evt);
            }
        });
        add(helpbutton);
    }// </editor-fold>//GEN-END:initComponents

    private void helpbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_helpbuttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton helpbutton;
    public javax.swing.JTextField textField;
    // End of variables declaration//GEN-END:variables
}
